---
title: "Data Viewer"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(leaflet)
library(dplyr)
library(ggplot2)
library(DT)
library(geojsonio)


# Create a color palette 'pal' for watersheds
pal <- colorFactor(palette = c("#1F77B4", "#AEC7E8", "#FF7F0E", "#FFBB78", 
                               "#2CA02C", "#98DF8A", "#D62728", "#FF9896", 
                               "#9467BD", "#C5B0D5", "#8C564B", "#C49C94", 
                               "#E377C2", "#F7B6D2", "#7F7F7F", "#C7C7C7", 
                               "#BCBD22", "#DBDB8D", "#17BECF", "#9EDAE5"), 
                   domain = NULL)

stations <- NULL
selected <- NULL
add_watersheds <- FALSE
add_stations <- FALSE

options(shiny.maxRequestSize = 30*1024^2)
```

Column {.sidebar data-width=425}
-----------------------------------------------------------------------

### **Instructions**

Select a station from the map on the left to retrieve monitoring data. You can use the bottom selector to plot particular constituents from that station.

#### **Load Files**

```{r}
fileInput("file1", "Load a Formatted Stations CSV File",
          accept = c("text/csv",
                     "text/comma-separated-values,text/plain",
                     ".csv")
          )
fileInput("file2", "Load a Formatted Monitoring Data CSV File",
          accept = c("text/csv",
                     "text/comma-separated-values,text/plain",
                     ".csv")
          )
```


#### **Plot**

```{r}

### Reference: https://stackoverflow.com/questions/51153184/dynamic-filters-and-reactive-plot-in-shiny
uiOutput("in1")

uiOutput("in2")

uiOutput("in3")

uiOutput("in4")

output$in1 <- renderUI({
  selectInput(inputId = "in_station",
              label = "StationCode", 
              choices = as.character(unique(data()$StationCode) %>% sort()),
              selected = NULL)
})

datasub <- reactive({
  data()[data()$StationCode == input$in_station, ]
})

output$in2 <- renderUI({
  selectInput(inputId = "in_analyte",
              label = "AnalyteName",
              choices = as.character(unique(datasub()$AnalyteName) %>% sort()),
              selected = NULL)
})

datasub2 <- reactive({
  datasub()[datasub()$AnalyteName == input$in_analyte, ]
})

output$in3 <- renderUI({
  selectInput(inputId = "in_weather",
              label = "WeatherCondition",
              choices = as.character(unique(datasub2()$WeatherCondition) %>% sort()),
              selected = NULL)
})

datasub3 <- reactive({
  datasub2()[datasub2()$WeatherCondition == input$in_weather, ]
})

output$in4 <- renderUI({
  selectInput(inputId = "in_units",
              label = "UnitName",
              choices = as.character(unique(datasub3()$UnitName) %>% sort()),
              selected = NULL)
})

datasub4 <- reactive({
  datasub3()[datasub3()$UnitName == input$in_units, ]
})

output$myplot <- shiny::renderPlot({
  ggplot2::ggplot(datasub4(), aes(SampleDate, Result)) + 
    geom_point() +
    labs(title = paste0("Station: ", input$in_station, " (", input$in_weather, " Weather)"), 
         subtitle = paste0("AnalyteName: ", input$in_analyte)) +
    ylab(paste0("Result (", input$in_units, ")")) + 
    xlab("Sample Date") +
    theme_light()
})

plotOutput("myplot")

```

#### **Statistics**
To be developed



Row {data-height=550}
-----------------------------------------------------------------------

### Map

```{r}

### Process station csv file
stations <- reactive({
  req(input$file1)
  read.csv(input$file1$datapath)
})

### Process monitoring data csv file
data <- reactive({
  req(input$file2)
  df <- read.csv(input$file2$datapath)
  df$SampleDate <- as.Date(df$SampleDate)

  df
})


output$mymap <- leaflet::renderLeaflet({
  
  ### Initialize Map
  m <- leaflet::leaflet() %>%
    leaflet::addProviderTiles("Hydda.Full") %>%
    leaflet::setView(-118.2437, 34.0522, zoom = 9)
  
  ### Add Watershed Polygons -- Currently Not In Use
  if (add_watersheds) {
    m <- m %>% 
      leaflet::addPolygons(data=watersheds, stroke = TRUE, weight = 0.25, 
                       smoothFactor = 0.5, fillOpacity = 0.35,
                       fillColor = ~pal(NAME), 
                       popup = ~paste("", NAME, "", ""))
  }

  ### Add Station Markers
  if (is.null(stations())) {
    return(NULL)
  } else {
    m <- m %>%
      leaflet::addMarkers(data=stations(), layerId = ~StationCode,
                      popup = ~paste("<b>Station Code</b>:", stations()$StationCode, "<br>",
                                     "<b>Alternate Station Names</b>: - <br>",
                               "<b>Waterbody</b>:", stations()$Waterbody, "<br>",
                               "<b>Watershed</b>: ", stations()$Watershed, "<br>",
                               "<b>Description:</b>", stations()$Description, "<br>"))
  }
  m
})



leafletOutput('mymap')

click_marker <- observeEvent(input$mymap_marker_click, {
    click <- input$mymap_marker_click
    
    table_selected <- data() %>%
      dplyr::filter(StationCode == click$id)
    
    ### Updated Data Table
    output$mytable <- DT::renderDataTable({
      
      DT::datatable(table_selected, extensions = 'Scroller', 
                    options = list(pageLength = 10, scrollX = 100, scrollY = 200, scroller = TRUE), rownames = FALSE) %>%
        DT::formatStyle(columns = colnames(.), fontSize = "50%")
    })
    
    return(click_marker)
})



```


Row {data-height=450}
-----------------------------------------------------------------------

### Monitoring Data

```{r}
output$mytable <- DT::renderDataTable({
      DT::datatable(data(), extensions = 'Scroller',
                    options = list(pageLength = 10, scrollX = 200, scrollY = 200, scroller = TRUE), rownames = FALSE) %>%
        DT::formatStyle(columns = colnames(.), fontSize = "50%")
    })

DTOutput("mytable")

```
